version: 2.1

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create and deploy the front end"
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name "bucket-${CIRCLE_WORKFLOW_ID:0:7}" \
            --parameter-overrides PipelineID="bucket-${CIRCLE_WORKFLOW_ID:0:7}"\
            
  copy_to_bucket:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Copy html file to S3 bucket"
          command: |
            aws s3 cp ./index.html s3://bucket-${CIRCLE_WORKFLOW_ID:0:7}
      
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Promote build to production"
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="bucket-${CIRCLE_WORKFLOW_ID:0:7}"

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yum -y install tar
            yum -y install gzip
      - run:
          name: "Clean up old front end"
          command: |
            echo ${deploymentID}
            aws s3 rm "s3://${deploymentID}" --recursive
workflows:
  myWorkflow:
    jobs:
        - create_and_deploy_front_end
        - copy_to_bucket:
            requires: [create_and_deploy_front_end]
        - promote_to_production:
            requires: [copy_to_bucket]
        - clean_up_old_front_end: 
            requires: [promote_to_production]