version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Create and deploy the front end"
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}" \
            --region us-west-2

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Get last deployment ID"
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text >> deploymentID.txt
      - persist_to_workspace:
          root: ./       
          paths:
            - deploymentID.txt
      
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Promote build to production"
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name production-distro \
            --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "Clean up old front end"
          command: |
            PreviousPipelineID=`cat deploymentID.txt` 
            aws s3 rm "s3://${PreviousPipelineID}" --recursive
            aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"
workflows:
  myWorkflow:
    jobs:
        - create_and_deploy_front_end
        - get_last_deployment_id:
            requires: [create_and_deploy_front_end]
        - promote_to_production:
            requires: [create_and_deploy_front_end]
        - clean_up_old_front_end: 
            requires: [promote_to_production]